#! /bin/sh
#set -x
cd $(dirname $0)
#./launcher

if [ $(pgrep -cx panel) -gt 1 ] ; then
#    printf "%s\n" "The panel is already running." >&2
#    exit 1
    pkill panel
fi

. ./panel_colors

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-dzen2}

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T[%s]' > "$PANEL_FIFO" &
clock -i 1 -sf 'S[%a, %d %b] [%H:%M:%S]' > "$PANEL_FIFO" &
./panel_info.sh > "$PANEL_FIFO" &

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | ./panel_bar | bar -d -f '-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1'
        ;;
    dzen2)
        PANEL_HEIGHT=16
        FONT_FAMILY='DejaVu Sans'
        FONT_SIZE=11
        PANEL_WIDTH=1555
        cat "$PANEL_FIFO" | ./panel_dzen2 -w $PANEL_WIDTH -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -x 0 -y 0 -w $PANEL_WIDTH -ta l -title-name "panel" -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND"
        ;;
esac
