#!/bin/bash
bspc monitor $MONITOR1 -d web code code code code code mail feeds chat music
bspc monitor $MONITOR2 -d code code code code code code code code code

# Configure both monitors at the same time
desktop_config() {
    bspc config $1 $2
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}

if [ -e "$BSPWM_DUMP" ] ; then
    bspc wm -l $BSPWM_DUMP
    rm $BSPWM_DUMP
fi

# add padding for polybar
bspc config -m $MONITOR1 top_padding 14

# Visual options (for all monitors)
desktop_config split_ratio 0.50
desktop_config border_width 1
desktop_config window_gap 4
desktop_config borderless_monocle true
desktop_config gapless_monocle true
desktop_config focus_follows_pointer false
#desktop_config click_to_focus true
desktop_config auto_alternate true
desktop_config auto_cancel true
desktop_config normal_border_color "#504339"
desktop_config active_border_color "#504339"
desktop_config focused_border_color "#fdf6e3"
#desktop_config presel_border_color "#2aa198" old - 0.9
desktop_config presel_feedback_color "#2aa198"
desktop_config urgent_border_color "#d70000"
desktop_config focused_locked_border_color "#cb4b16"
desktop_config normal_frame_opacity 0.0
desktop_config focused_frame_opacity 0.2
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config click_to_focus true

# Rules
bspc rule -a Gimp state=floating follow=no
bspc rule -a Skype desktop=chat
bspc rule -a skypeforlinux desktop=chat
bspc rule -a Pidgin desktop=chat
bspc rule -a ViberPC desktop=chat
bspc rule -a discord desktop=chat
bspc rule -a Firefox desktop=web
bspc rule -a Thunderbird desktop=mail
bspc rule -a Liferea desktop=feeds
bspc rule -a Spotify desktop=music

bspc config external_rules_command ~/.config/bspwm/rules/popups.sh

$HOME/.config/polybar/launch.sh &

# Autorun on startup
dunst &
nm-applet &
blueman-applet &
#sh -c '$HOME/.fehbg' &
#sh -c '$HOME/scripts/wallpaper_focus.sh' &
nitrogen --restore &
#fbxkb & # icon
#unclutter -idle 5 -noevents -root &
#volumeicon & # icon
#skype & # icon
#pidgin & # icon
#liferea & # icon
#thunderbird &
#firefox &
#shutter & # icon
#spotify &
