#!/bin/bash
# Based on https://github.com/meskarune/i3lock-fancy

IMAGE=/tmp/i3lock.png

# Blur examples: http://www.imagemagick.org/Usage/blur/#blur_args
scrot $IMAGE
convert $IMAGE -level 0%,100%,0.6 -blur 0x4 - | composite -geometry +847+506 $(dirname $0)/lock.png - $IMAGE 

#xautolock -disable
if [ $? -eq 0 ]; then
    i3lock -e -i $IMAGE
else 
    i3lock -e -c 000000 
fi
#xautolock -enable

rm $IMAGE
