#!/bin/bash
# Based on https://github.com/meskarune/i3lock-fancy

IMAGE=/tmp/i3lock.png

# TODO - sometimes multiple instances of i3lock remain running
#killall i3lock

# Blur examples: http://www.imagemagick.org/Usage/blur/#blur_args
scrot $IMAGE
# bluring is too slow on large images (like two HD desktops..):
# real    0m5.782s
# user    0m7.407s
# sys     0m0.377s
# convert $IMAGE -level 0%,100%,0.6 -blur 0x4 - | composite -geometry +847+506 $(dirname $0)/lock.png - $IMAGE 

# Time:
# real    0m3.739s
# user    0m4.443s
# sys     0m0.377s
# 12.5x12.5% -> 800x800% with blur 0x2 is another seconds faster, but too blurred..
convert $IMAGE -level 0%,100%,0.6 -resize 25x25% -blur 0x4 -resize 400x400% - | composite -geometry +847+506 $(dirname $0)/lock.png - - | composite -geometry +2040+0 $(dirname $0)/dragon_lock.png - $IMAGE

if [ $? -eq 0 ]; then
    i3lock -e -n -i $IMAGE
else 
    i3lock -e -n -c 000000 
fi

rm $IMAGE
